services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-todo
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - mynet

networks:
  mynet: